### PR TITLE
break out if automation fails

### PR DESCRIPTION
**Pull request by gtmanfred**

### CODE REVIEW

**Comment by gtmanfred** [comment]
I should have added this before, I didn't think about it until we were looking at adding a timeout.

But yeah, servermill will timeout at about 5 minutes anyway and set the metadata to Build Error.

if it does that, then yall should just break, because we have to manually remediate.

Thanks
Daniel

**Comment by gtmanfred** [comment]
Verifying that that value is always set to 'Build Error' on failures real quick.

**Comment by gtmanfred** [comment]
It is, it will be set to build error, and then another tag is applied with what part failed.

**Comment by rshade** [comment]
sweet, will merge as soon as travis gets done with it

**Pull request merged**
